title: "An Invitation to Category Theory"
description: "Formalized in Agda with clickable, interactive code"
baseurl: "/an-invitation-to-category-theory"
url: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true  # We use Agda's syntax highlighting
  parse_block_html: true  # Allow HTML in markdown (important for Agda code blocks)

# Include Agda-generated files
include:
  - docs

# Exclude source files from the build
exclude:
  - src
  - .github
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts
  - category-theory.agda-lib
  - EMBEDDING-GUIDE.md
