name: Build and Deploy Agda Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Get GHC and Agda versions
        id: versions
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ghc cabal-install
          GHC_VERSION=$(ghc --numeric-version)
          cabal update
          AGDA_VERSION=$(cabal list --simple-output agda | grep '^agda ' | head -1 | awk '{print $2}')
          echo "ghc=$GHC_VERSION" >> $GITHUB_OUTPUT
          echo "agda=$AGDA_VERSION" >> $GITHUB_OUTPUT
          echo "GHC version: $GHC_VERSION"
          echo "Latest Agda version: $AGDA_VERSION"

      - name: Cache Cabal and Agda
        id: cache-agda
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            ~/.cabal/packages
            ~/.local/bin
            ~/.local/state/cabal/store
          key: ${{ runner.os }}-agda-${{ steps.versions.outputs.agda }}-ghc-${{ steps.versions.outputs.ghc }}
          restore-keys: |
            ${{ runner.os }}-agda-

      - name: Log cache status
        run: |
          echo "Agda cache hit: ${{ steps.cache-agda.outputs.cache-hit }}"
          if [ "${{ steps.cache-agda.outputs.cache-hit }}" == "true" ]; then
            echo "Agda restored from cache"
          else
            echo "Agda cache miss - will install from source"
          fi

      - name: Install Agda
        if: steps.cache-agda.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss - installing Agda..."
          cabal install Agda

      - name: Verify Agda installation
        run: |
          echo "Checking if Agda binary exists..."
          ls -la ~/.local/bin/agda* || echo "No agda binary found in ~/.local/bin"
          echo "Adding ~/.local/bin to PATH..."
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Get latest Agda stdlib version
        id: stdlib-version
        run: |
          STDLIB_VERSION=$(git ls-remote --tags --refs --sort="v:refname" https://github.com/agda/agda-stdlib.git | tail -n1 | sed 's/.*\///')
          echo "version=$STDLIB_VERSION" >> $GITHUB_OUTPUT
          echo "Latest agda-stdlib version: $STDLIB_VERSION"

      - name: Cache Agda standard library
        id: cache-stdlib
        uses: actions/cache@v4
        with:
          path: ~/.agda
          key: ${{ runner.os }}-agda-stdlib-${{ steps.stdlib-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-agda-stdlib-

      - name: Log stdlib cache status
        run: |
          echo "Stdlib cache hit: ${{ steps.cache-stdlib.outputs.cache-hit }}"
          if [ "${{ steps.cache-stdlib.outputs.cache-hit }}" == "true" ]; then
            echo "Agda stdlib restored from cache"
          else
            echo "Stdlib cache miss - will install from source"
          fi

      - name: Install Agda standard library
        if: steps.cache-stdlib.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss - installing Agda stdlib..."
          mkdir -p ~/.agda
          cd ~/.agda
          git clone --depth 1 --branch ${{ steps.stdlib-version.outputs.version }} https://github.com/agda/agda-stdlib.git
          cd agda-stdlib
          echo "name: standard-library" > standard-library.agda-lib
          echo "include: src" >> standard-library.agda-lib
          echo "$HOME/.agda/agda-stdlib/standard-library.agda-lib" > ~/.agda/libraries
          echo "standard-library" > ~/.agda/defaults

      - name: Verify stdlib installation
        run: |
          echo "Checking stdlib configuration..."
          ls -la ~/.agda/ || echo "~/.agda/ not found"
          cat ~/.agda/libraries || echo "libraries file not found"
          cat ~/.agda/defaults || echo "defaults file not found"

      - name: Generate HTML documentation
        run: |
          echo "Current PATH: $PATH"
          echo "Contents of ~/.local/bin:"
          ls -la ~/.local/bin/ || echo "~/.local/bin not found"
          echo "Setting PATH to include ~/.local/bin..."
          export PATH="$HOME/.local/bin:$PATH"
          echo "Updated PATH: $PATH"
          echo "Testing agda command..."
          which agda || echo "agda not found in PATH"
          agda --version
          echo "Generating HTML documentation..."
          agda --html --html-dir=docs --html-highlight=auto src/Everything.agda

      - name: Copy custom assets
        run: |
          if [ -d "site-assets" ]; then
            cp -r site-assets/* docs/ || true
          fi

      - name: Add Jekyll front matter to markdown files
        run: |
          chmod +x scripts/add-jekyll-frontmatter.sh
          ./scripts/add-jekyll-frontmatter.sh

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
